[package]
name = "text-paint"
version = "0.1.0"
edition = "2021"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]

[dependencies]
meap = "0.5"
toml = "0.5"
nom = "7.1"

[dependencies.gridbugs]
version = "0.5"
features = [
    "chargrid",
    "chargrid_wgpu",
    "chargrid_ansi_terminal",
    "rgb_int",
]
